DROP DATABASE IF EXISTS employee_Tracker_db;
CREATE DATABASE employee_Tracker_db;

USE employee_Tracker_db;

CREATE TABLE IF NOT EXISTS department (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
name VARCHAR(30),
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
title VARCHAR(30),
salary DECIMAL(12, 2),
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS employee (
id INTEGER(11) AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30),
last_name VARCHAR(30),
role INTEGER(11),
manager_id INTEGER(11) NULL,
PRIMARY KEY (id)
);